type WarehouseLog = {
  id: number;
  company_id: number;
  type: number;
  relation_id: number;
  relation_code: string;
  target: string;
  target_id: number;
  target_code: string;
  warehouse_id: number;
  project_id: number;
  sales_contract_id: number;
  sales_order_id: number;
  material_id: number;
  material_sku_id: number;
  batch_no: string;
  num: number;
  unit: string;
  status: number;
  created_id: number;
  deleted_at: string;
  updated_at: string;
  created_at: string;
  btn_power: BtnPower;
  created_user: CreateUser | null;
  company: BlockCompany | null;
  project: BlockProject | null;
  sales_contract: BlockSalesContract | null;
  sales_order: BlockSalesOrder | null;
  warehouse: {
    id: number;
    name: string;
    short_name: string;
  } | null;
  material: BlockMaterail | null;
  material_sku: BlockMaterialSku | null;
  line_unit: LineUnit[];
  line_inventory_unit: LineUnit[];
};
