declare const FRAMEWORK_WEBPACK_ENTRY: string;
declare const FRAMEWORK_PRELOAD_WEBPACK_ENTRY: string;
declare const ADMIN_WEBPACK_ENTRY: string;
declare const ADMIN_PRELOAD_WEBPACK_ENTRY: string;

export default {
  FRAMEWORK_WEBPACK_ENTRY,
  FRAMEWORK_PRELOAD_WEBPACK_ENTRY,
  ADMIN_WEBPACK_ENTRY,
  ADMIN_PRELOAD_WEBPACK_ENTRY,
};
