type ReceiveOrder = {
  id: number;
  company_id: number;
  type: number;
  code: string;
  name: string;
  bill_date: string;
  table: string;
  table_id: number;
  company_name: string;
  company_address: string;
  linkman: string;
  phone: string;
  amount: string;
  remark: string;
  is_approve: 0 | 1;
  status: number;
  created_id: number;
  deleted_at: string;
  updated_at: string;
  created_at: string;
  btn_power: BtnPower;
  target_code: string;
  target: string;
  created_user: BlockCreateUser;
  company: BlockCompany;
  sales_contract: BlockSalesContract;
  project: BlockProject;
  sales_order: BlockSalesOrder;
  type_show: string;
};
