type SalesContractDetail = {
  remark: string;
  id: number;
  company_id: number;
  client_id: number;
  project_id: number;
  sales_contract_id: number;
  material_id: number;
  material_sku_id: number;
  standard: string;
  num: number;
  price: string;
  amount: string;
  status: number;
  created_id: number;
  deleted_at: string;
  updated_at: string;
  created_at: string;
  btn_power: BtnPower;
  created_user: CreateUser;
  company: Company | null;
  project: Project | null;
  material: Materail | null;
  material_sku: MaterialSku | null;
  client: Client;
  demand_date: string;
  sales_contract: SalesContract;
  line_unit: LineUnit[];
  attr_snapshoot: AttrSnapshoot;
};
