type SalesOrderDetail = {
  attr_snapshoot: AttrSnapshoot;
  id: number;
  company_id: number;
  client_id: number;
  project_id: number;
  sales_contract_id: number;
  sales_contract_detail_id: number;
  sales_order_id: number;
  material_id: number;
  material_sku_id: number;
  num: number;
  price: string;
  standard: string;
  demand_date: string;
  rate: number;
  tax: string;
  amount: string;
  freight: string;
  freight_rate: number;
  freight_tax: string;
  total_tax: string;
  total_no_tax_amount: number;
  total_amount: string;
  remark: string;
  status: number;
  created_id: number;
  updated_at: string;
  deleted_at: string;
  created_at: string;
  btn_power: BtnPower;
  created_user: BlockCreateUser;
  company: BlockCompany;
  client: BlockClient | null;
  project: BlockProject | null;
  sales_contract_detail: {
    id: number;
    num: number;
    price: number;
    amount: number;
    standard: string;
  } | null;
  sales_order: BlockSalesOrder;
  material: BlockMaterail | null;
  material_sku: BlockMaterialSku | null;
  sales_contract: BlockSalesContract;
  produce_num: string;
  purchase_num: string;
  line_unit: LineUnit[];
  line_produce_unit: LineUnit[];
  line_purchase_unit: LineUnit[];
};
