type SupplierContact = {
  id: number;
  company_id: number;
  supplier_id: number;
  name: string;
  job_title: string;
  phone: string;
  wechat: string;
  ID_card: string;
  is_main: number;
  remark: string;
  status: number;
  created_id: number;
  deleted_at: string;
  updated_at: string;
  created_at: string;
  btn_power: BtnPower;
  created_user: BlockCreateUser;
  company: BlockCompany;
  supplier: BlockSupplier;
};
